# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a25967a7ced4b9ebb554555aea66e872b2c4225d9114127333519d0ca48c16393e49b0988e9fa8e73836309564c680f74ad9598f359b926dc9631fc0dcc4d098

test:
  secret_key_base: 9ad58e51e2641279bf9ac7a9ae845e0002e841b52e0edf62cb96ffbbebb8fe6c26e8bc7dc01ae8c4dcc6ca8980c9ae6c0548e74f6d1aaf61b0297efd02da715c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
